<Project>

  <PropertyGroup>
    <IsCodeAnalyzer>True</IsCodeAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <None Update="lib/**/*" Pack="false" />
    <None Include="$(OutputPath)$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    <None Include="$(OutputPath)$(AssemblyName).pdb" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    <None Include="AnalyzerReleases.Shipped.md" Pack="true" PackagePath="analyzers/dotnet/cs"
          Condition="Exists('AnalyzerReleases.Shipped.md')" />
    <None Include="AnalyzerReleases.Unshipped.md" Pack="true" PackagePath="analyzers/dotnet/cs"
          Condition="Exists('AnalyzerReleases.Unshipped.md')" />
  </ItemGroup>

</Project>
